# Generated by Django 4.0.6 on 2022-07-13 15:30

import app.card.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', app.card.fields.CardNumberField(unique=True)),
                ('start_date', models.DateTimeField()),
                ('expired_date', app.card.fields.CardExpiryField()),
                ('code', app.card.fields.SecurityCodeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('card_status', models.PositiveSmallIntegerField(choices=[(0, 'Unactive'), (1, 'Active'), (2, 'Expired')])),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Products'), (2, 'Auto'), (3, 'Charity'), (4, 'Budget'), (5, 'Shipments'), (6, 'Cash'), (7, 'Transfers'), (8, 'Stationery'), (9, 'Cafe'), (10, 'Flowers'), (11, 'Movies'), (12, 'Books'), (13, 'Utility'), (14, 'Courier'), (15, 'Medicine'), (16, 'Clothes'), (17, 'Stitching'), (18, 'Electronics'), (19, 'Credit'), (20, 'Travels'), (21, 'Parts'), (22, 'Mobile'), (23, 'Marketing'), (24, 'Repair'), (25, 'Entertainment'), (26, 'Taxi'), (27, 'Pets'), (28, 'Fines'), (29, 'Jewerly'), (30, 'Duty Free')], default=0)),
                ('name', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 13, 15, 30, 26, 623158, tzinfo=utc))),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.card')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
